### PR TITLE
Added composer

### PR DESCRIPTION
**Pull request by thedava**
https://github.com/pear/Text_Diff/pull/2

### CODE REVIEW

**Comment by thedava** [comment]
I would also recommend to add this repository as "pear/Text_Diff" to packagist.org

**Comment by cweiske** [comment]
The package still needs to be usable via PEAR, which means the `require_once` statements have to be kept. What you can do instead is trigger the autoloader by checking with `class_exists` before doing the `require_once` call.

Also I don't think the tests need to be adjusted when you want to run them from a git checkout.

**Comment by thedava** [comment]
The compatibility to pear makes sense. I didn't thought about that. I optimized the includes and reverted the tests.

**Comment by cweiske** [comment]
Thanks for your patch. I've merged it into stable.

**Comment by bretrzaun** [comment]
To complete this, it would be great if this repository would be submitted as "pear/Text_Diff" to packagist.org.

**Pull request closed without merging**
